"use client"

import { useState,useEffect } from "react"
import axios from "axios"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export default function Home(){

const [tab,setTab]=useState("scan")

const [url,setUrl]=useState("")
const [loading,setLoading]=useState(false)
const [result,setResult]=useState<any>(null)

const [framework,setFramework]=useState("ISO 27001")
const [questions,setQuestions]=useState<any[]>([])
const [answers,setAnswers]=useState<any>({})
const [assessmentResult,setAssessmentResult]=useState<any>(null)

const [privacyText,setPrivacyText]=useState("")

const [mouse,setMouse]=useState({x:0,y:0})

/* ------------------ POINTER GLOW ------------------ */

useEffect(()=>{

const move=(e:any)=>{
setMouse({x:e.clientX,y:e.clientY})
}

window.addEventListener("mousemove",move)
return()=>window.removeEventListener("mousemove",move)

},[])

/* ------------------ LOAD PRIVACY POLICY ------------------ */

useEffect(()=>{

fetch("/privacy_policy.md")
.then(res=>res.text())
.then(text=>setPrivacyText(text))

},[])

/* ------------------ LOAD QUESTIONS ------------------ */

useEffect(()=>{

axios
.get(`http://127.0.0.1:8000/framework/${framework}`)
.then(res=>{

setQuestions(res.data.questions)

const initial:any={}
res.data.questions.forEach((q:any)=>{
initial[q.id]=""
})

setAnswers(initial)

})

},[framework])

/* ------------------ SCAN WEBSITE ------------------ */

const runScan=async()=>{

if(!url) return

setLoading(true)

try{

const res=await axios.post(
"http://127.0.0.1:8000/scan",
{url}
)

setResult(res.data)

}catch(err){

console.log(err)
alert("Scanner failed")

}

setLoading(false)

}

/* ------------------ SELF ASSESSMENT ------------------ */

const runAssessment=async()=>{

const formatted:any={}

Object.keys(answers).forEach(key=>{
formatted[key]=answers[key]==="Yes"
})

try{

const res=await axios.post(
"http://127.0.0.1:8000/self-assessment",
{
framework,
answers:formatted
}
)

setAssessmentResult(res.data)

}catch{

alert("Assessment API error")

}

}

/* ------------------ PDF REPORT ------------------ */

const downloadReport=()=>{

if(!result) return

const pdf:any=new jsPDF()

/* -------- METADATA -------- */

const scanDate=new Date()

const formattedDate=scanDate.toLocaleDateString()
const formattedTime=scanDate.toLocaleTimeString()

const reportId="AUD-"+Math.floor(Math.random()*100000)

/* -------- HEADER -------- */

pdf.setFontSize(22)
pdf.text("AuditApp Security Report",20,20)

pdf.setFontSize(12)

pdf.text(`Target Website: ${url}`,20,35)
pdf.text(`Scan Date: ${formattedDate}`,20,42)
pdf.text(`Scan Time: ${formattedTime}`,20,49)
pdf.text(`Report ID: ${reportId}`,20,56)
pdf.text(`Generated By: AuditApp Scanner Engine`,20,63)

/* -------- SECURITY TABLE -------- */

autoTable(pdf,{
startY:75,
head:[["Security Header","Status"]],
body:[
...(result.detected_security||[]).map((i:any)=>[i,"Detected"]),
...(result.missing_security||[]).map((i:any)=>[i,"Missing"])
]
})

/* -------- PRIVACY TABLE -------- */

autoTable(pdf,{
startY:(pdf as any).lastAutoTable.finalY+10,
head:[["Privacy Component","Status"]],
body:[
...(result.detected_privacy||[]).map((i:any)=>[i,"Detected"]),
...(result.missing_privacy||[]).map((i:any)=>[i,"Missing"])
]
})

/* -------- FOOTER -------- */

const pageHeight=pdf.internal.pageSize.height

pdf.setFontSize(10)

pdf.text(
"Generated by AuditApp — Compliance & Security Intelligence Platform",
20,
pageHeight-10
)

pdf.save("audit_report.pdf")

}

/* ------------------ INTEL HELPERS ------------------ */

const scanCoverage=()=>{
if(!result) return ""
const total=(result.detected_security?.length||0)+(result.missing_security?.length||0)
return `${result.detected_security?.length||0} / ${total} headers detected`
}

const complianceImpact=()=>{
if(!result) return []

const issues=[]

if(result.missing_privacy?.includes("Consent")) issues.push("GDPR")
if(result.missing_privacy?.includes("Cookies")) issues.push("CCPA")
if(result.missing_security?.length>0) issues.push("ISO 27001","SOC 2")

return [...new Set(issues)]
}

const recommendations=()=>{
if(!result) return []

const rec=[]

if(result.missing_privacy?.includes("Consent")) rec.push("Implement cookie consent banner")
if(result.missing_privacy?.includes("Cookies")) rec.push("Provide cookie usage disclosure")
if(result.missing_security?.includes("Content Security Policy")) rec.push("Add Content-Security-Policy header")
if(result.missing_security?.includes("Referrer Policy")) rec.push("Add Referrer-Policy header")

return rec
}

/* ------------------ UI ------------------ */

return(

<main className="relative min-h-screen flex flex-col items-center pt-24 pb-40 bg-[#F5EFE6] text-gray-900">

<div
className="pointer-events-none fixed inset-0"
style={{
background:`radial-gradient(600px circle at ${mouse.x}px ${mouse.y}px, rgba(139,92,246,0.18), transparent 40%)`
}}
/>

<h1 className="text-6xl font-bold mb-4 bg-gradient-to-r from-indigo-500 via-purple-500 to-indigo-400 text-transparent bg-clip-text">
AuditApp
</h1>

<p className="text-gray-700 mb-12 text-center">
Compliance & Security Intelligence Platform for startups and businesses.
</p>

<div className="flex gap-6 mb-12">

<button onClick={()=>setTab("scan")} className={`px-6 py-3 rounded-xl ${tab==="scan"?"bg-indigo-500 text-white":"bg-white/30 backdrop-blur-xl"}`}>
Website Scanner
</button>

<button onClick={()=>setTab("assessment")} className={`px-6 py-3 rounded-xl ${tab==="assessment"?"bg-purple-500 text-white":"bg-white/30 backdrop-blur-xl"}`}>
Compliance Assessment
</button>

<button onClick={()=>setTab("privacy")} className={`px-6 py-3 rounded-xl ${tab==="privacy"?"bg-gray-800 text-white":"bg-white/30 backdrop-blur-xl"}`}>
Privacy Policy
</button>

</div>

{tab==="scan"&&(

<div className="flex flex-col items-center w-full">

<div className="bg-white/20 backdrop-blur-2xl shadow-xl p-8 rounded-3xl w-[520px]">

<input
value={url}
onChange={(e)=>setUrl(e.target.value)}
placeholder="Enter company website"
className="w-full p-4 rounded-xl border border-gray-300 mb-4 bg-white"
/>

<button
onClick={runScan}
className="w-full p-4 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-500 text-white"
>
{loading?"Scanning...":"Start Security Scan"}
</button>

</div>

{result&&(

<>

<div className="grid md:grid-cols-4 grid-cols-2 gap-6 mt-16 max-w-6xl">

<Score title="Privacy Score" value={`${result.privacy_score}%`} />
<Score title="Security Score" value={`${result.security_score}%`} />
<Score title="Overall Score" value={`${result.overall_score}%`} />
<Score title="Risk Grade" value={result.risk_grade} />

</div>

<div className="grid md:grid-cols-4 gap-6 mt-10 max-w-6xl">

<Card title="Detected Privacy Findings" items={result.detected_privacy} />
<Card title="Missing Privacy Components" items={result.missing_privacy} />
<Card title="Detected Security Headers" items={result.detected_security} />
<Card title="Missing Security Headers" items={result.missing_security} />

</div>

<div className="grid md:grid-cols-3 gap-6 mt-10 max-w-6xl">

<IntelCard title="Scan Coverage" items={[scanCoverage()]} />
<IntelCard title="Compliance Impact" items={complianceImpact()} />
<IntelCard title="Recommendations" items={recommendations()} />

</div>

<button
onClick={downloadReport}
className="mt-12 bg-green-500 px-8 py-4 rounded-xl text-white hover:scale-105 transition"
>
Download Audit Report
</button>

</>

)}

</div>

)}

{tab==="assessment"&&(

<div className="bg-white/20 backdrop-blur-2xl shadow-xl p-8 rounded-3xl w-[550px]">

<h2 className="text-xl font-semibold mb-6">
Compliance Self Assessment
</h2>

<select
value={framework}
onChange={(e)=>setFramework(e.target.value)}
className="w-full p-3 rounded-xl mb-6 bg-white"
>

<option>ISO 27001</option>
<option>GDPR (EU)</option>
<option>SOC 2</option>
<option>DPDP (India)</option>
<option>CCPA (California)</option>

</select>

{questions.map((q:any)=>(
<Question
key={q.id}
label={q.question}
value={answers[q.id]}
onChange={(v:any)=>setAnswers({...answers,[q.id]:v})}
/>
))}

<button
onClick={runAssessment}
className="mt-6 bg-purple-500 px-6 py-3 rounded-xl text-white"
>
Calculate Risk
</button>

{assessmentResult&&(

<div className="mt-6">

<p className="font-semibold">
Risk Level: {assessmentResult.risk_level}
</p>

<p>
Risk Percentage: {assessmentResult.risk_percentage.toFixed(2)}%
</p>

</div>

)}

</div>

)}

{tab==="privacy"&&(

<div className="max-w-4xl bg-white/20 backdrop-blur-2xl p-10 rounded-2xl shadow whitespace-pre-wrap">
{privacyText}
</div>

)}

</main>

)

}

/* ---------- COMPONENTS ---------- */

function Score({title,value}:any){

let color="text-gray-800"
const num=parseInt(value)

if(title==="Privacy Score"){
if(num>=70) color="text-green-600"
else if(num>=40) color="text-orange-500"
else color="text-red-600"
}

if(title==="Security Score"){
if(num>=80) color="text-green-600"
else if(num>=50) color="text-orange-500"
else color="text-red-600"
}

if(title==="Overall Score"){
if(num>=75) color="text-green-600"
else if(num>=50) color="text-orange-500"
else color="text-red-600"
}

if(title==="Risk Grade"){

if(value==="A") color="text-green-600"
else if(value==="B") color="text-yellow-600"
else if(value==="C") color="text-orange-600"
else color="text-red-600"

}

return(
<div className="bg-white/20 backdrop-blur-2xl rounded-2xl p-6 text-center shadow-lg hover:scale-105 transition">
<h3 className="text-gray-600">{title}</h3>
<p className={`text-3xl font-bold ${color}`}>{value}</p>
</div>
)

}

function Card({title,items}:any){

return(

<div className="bg-white/20 backdrop-blur-2xl rounded-2xl p-6 shadow-lg">

<h3 className="font-semibold mb-4">{title}</h3>

<ul className="list-disc ml-6 space-y-2 text-sm">

{items?.length===0&&<li>None detected</li>}

{items?.map((i:any,index:number)=>(
<li key={index}>{i}</li>
))}

</ul>

</div>

)

}

function IntelCard({title,items}:any){

return(

<div className="bg-white/20 backdrop-blur-2xl rounded-2xl p-6 shadow-lg">

<h3 className="font-semibold mb-4">{title}</h3>

<ul className="list-disc ml-6 space-y-2 text-sm">

{items?.length===0&&<li>No issues detected</li>}

{items?.map((i:any,index:number)=>(
<li key={index}>{i}</li>
))}

</ul>

</div>

)

}

function Question({label,value,onChange}:any){

return(

<div className="mb-5">

<label className="block mb-2">{label}</label>

<select
value={value}
onChange={(e)=>onChange(e.target.value)}
className="w-full p-3 rounded-xl bg-white"
>

<option value="">Select</option>
<option>Yes</option>
<option>No</option>

</select>

</div>

)

}